Use consistent file naming of documentation translations.
LinuxCNC/linuxcnc pull request #1346
Opened 2021-10-31 16:04 UTC by petterreinholdtsen

Use '_XX' instead of '-XX' consistently.

If there were several translations of the same file, the '-XX' one was deleted
without considering which translation is most up to date.

Fixes #1331

2021-10-31 19:01 UTC, petterreinholdtsen commented
This pull request will need an update after the build problem workaround in #1345 is merged.

2021-11-01 04:43 UTC, SebKuzminsky commented
Oops, I reimplemented parts of this PR independently and pushed to master.  This PR does a couple of extra things that I did not do (rename some SVGs to follow the "_<lang>" convention, possibly other things).  Please rebase and I'll take a look at what's left here.

2021-11-01 05:55 UTC, petterreinholdtsen commented
[Sebastian Kuzminsky]
> Oops, I reimplemented parts of this PR independently and pushed to
> master.  This PR does a couple of extra things that I did not do
> (rename some SVGs to follow the "_<lang>" convention, possibly other
> things).  Please rebase and I'll take a look at what's left here.

Done.

--
Happy hacking
Petter Reinholdtsen

2021-11-01 14:04 UTC, SebKuzminsky requested changes
Thanks for working on this, it's very close to ready.

2021-11-01 14:04 UTC, SebKuzminsky commented on docs/src/index_cn.tmpl
> +			<LI><A class="tooltips" HREF="config/pncconf_cn.html">Mesa Configuration Wizard<span>For Mesa Servo &amp; Stepper Machines</span></A>
All four of these files (`{step,pnc}conf{-,_}cn`) don't exist - just another issue with the Chinese translation.  For now the links should point to the english (untranslated) versions.

2021-11-01 14:04 UTC, SebKuzminsky commented on debian/extras/linuxcnc.files
> +usr/share/icons/hicolor/scalable/apps/linuxcnc_cn.svg
These renames require that you also update the Icon filenames in the .desktop files in `debian/extras/usr/share/applications/`.

2021-11-01 15:23 UTC, smoe reviewed
Done.

2021-11-02 07:08 UTC, petterreinholdtsen commented
I've updated the ones you discovered, and renamed a few more files according to the new notation.  Hope I got it all now.

2021-11-02 11:02 UTC, smoe commented
Well. The .txt -> .adoc rename PR https://github.com/LinuxCNC/linuxcnc/pull/1344 from what I see has these already covered. These rebases and manual checks meant far more work than the original effort to perform the rename in a for loop and sed on the includes. This was a whole morning that I cannot invest again. I just hope this wasn't the same for you now, @petterreinholdtsen .

2021-11-02 12:04 UTC, petterreinholdtsen commented
[Steffen Möller]
> Well. The .txt -> .adoc rename PR
> https://github.com/LinuxCNC/linuxcnc/pull/1344 from what I see has
> these already covered. These rebases and manual checks meant far more
> work than the original effort to perform the rename in a for loop and
> sed on the includes. This was a whole morning that I cannot invest
> again. I just hope this wasn't the same for you now,
> @petterreinholdtsen .

I am perfectly happy with the txt->adoc rename to happen first, and can
rebase these changes quite quickly.

-- 
Happy hacking
Petter Reinholdtsen

2021-11-04 17:14 UTC, SebKuzminsky commented
> These rebases and manual checks meant far more work than the original effort to perform the rename in a for loop and sed on the includes. This was a whole morning that I cannot invest again.

I'm sorry if the order I merged things in caused extra work for you, that was not my intent.  :-(

2021-11-04 17:48 UTC, SebKuzminsky commented
@petterreinholdtsen, thank you for these updates.

2021-11-04 17:49 UTC, merged