Add files via upload
LinuxCNC/linuxcnc pull request #1422
Opened 2021-12-02 16:14 UTC by romanetz

Colorcnc driver and firmware source

2021-12-02 18:22 UTC, SebKuzminsky commented
Hi @romanetz!  Can you give us a hint what this is about?  What's a Colorcnc?

2021-12-02 18:58 UTC, romanetz commented
Very short description: https://forum.linuxcnc.org/27-driver-boards/44422-colorcnc
So, it's a "hack" firmware and hal driver for colorlight 5a-75b board https://aliexpress.ru/item/32331955683.html
Firmware and driver is tested

2021-12-02 19:17 UTC, SebKuzminsky requested changes
This is great - thank you!!

Please add a bit of documentation describing what hardware this driver & firmware is for, how to connect it to LinuxCNC, and how to use it.  a README In the source directory would be enough.

We need to integrate this with the LinuxCNC build system and packaging infrastructure.  I can help with this if you want.

2021-12-02 19:17 UTC, SebKuzminsky commented on src/hal/drivers/colorcnc-firmware/litex_setup.py
> +#!/usr/bin/env python3
Please add a copyright notice and license.

2021-12-02 19:17 UTC, SebKuzminsky commented on src/hal/drivers/colorcnc-firmware/stepgen.v
> +//    Copyright 2007 Jeff Epler <jepler@unpythonic.net>
Is this a copy of Jeff's original, or has it been modified?  If it's been modified, please add copyrights for the people doing the modifying.

2021-12-02 19:17 UTC, SebKuzminsky commented on src/hal/drivers/colorcnc.c
> +*/
Add copyright and license (GPL is preferred for this project).

2021-12-02 19:17 UTC, SebKuzminsky commented on src/hal/drivers/colorcnc.h
> +#define driver_NAME "colorcnc"
Please add copyright & license (GPL preferred).

2022-07-15 07:23 UTC, petterreinholdtsen commented
Do you plan to update this pull request based on the comments received?  Half a year have passed with no updates, so I thought it best to ask.

I would suggest to format the install instructions (and the already requested README) in asciidoc format to match most of the other documentation in the project.

2022-08-13 13:07 UTC, petterreinholdtsen commented
@romanetz Ping?  Please let us know what your plans for this patch are.

2022-08-16 11:37 UTC, romanetz commented
> Do you plan to update this pull request based on the comments received? Half a year have passed with no updates, so I thought it best to ask.
> 
> I would suggest to format the install instructions (and the already requested README) in asciidoc format to match most of the other documentation in the project.

yes. there is a discussion on the forum https://forum.linuxcnc.org/27-driver-boards/44422-colorcnc-colorlight-5a-75e-5a-75b-as-fpga-controller-board

2022-11-08 06:40 UTC, petterreinholdtsen commented
@romanetz Do you have a estimate on when you plan to update the code according to the requested changes from @SebKuzminsky ?

2022-11-08 18:37 UTC, andypugh commented
It's probably worth looking at the forum thread, there seem to be updated versions of the same basic idea available. We could add both to LinuxCNC but that might be confusing.

2022-12-07 06:08 UTC, petterreinholdtsen commented
So, who is looking at the forum thread, and was is expected to come out of that?  Will this pull request be updated or a new one created?

2023-01-04 08:02 UTC, petterreinholdtsen commented
Any news here?

2023-06-26 21:18 UTC, luzpaz commented
Any ETA on this ?

2023-06-26 21:51 UTC, andypugh commented
@luzpaz We seem to be waiting for updates from @romanetz

2024-09-24 13:27 UTC, luzpaz commented
ping @romanetz

2024-09-24 18:06 UTC, romanetz commented
Well. As of now, I suggest to remove this PR from the tree as the project has evolved into LitexCNC.

2024-10-11 20:07 UTC, luzpaz commented
@romanetz can you provide link ?

2024-10-13 18:20 UTC, andreygursky commented
Perhaps, https://github.com/Peter-van-Tol/LiteX-CNC.

2025-01-05 23:14 UTC, andypugh commented
I am going to close this, as suggested. 

But would very much like to see a PR to incorporate LiteX-CNC

2025-01-05 23:14 UTC, closed without merging