Make latency-histogram available as Linux menu entry
LinuxCNC/linuxcnc pull request #1780
Opened 2022-06-28 13:47 UTC by petterreinholdtsen

This provide a XDG menu entry for latency-histogram alongside the
latency-test program

Solves Debian bug #1013911.

2022-06-28 13:47 UTC, petterreinholdtsen commented
See also https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1013911 .

2022-06-28 14:49 UTC, SebKuzminsky requested changes

2022-06-28 14:49 UTC, SebKuzminsky commented on share/applications/linuxcnc-latency-histogram.desktop.in
> +Exec=@EMC2_LATENCY_SCRIPT@
Should be `@EMC2_LATENCY_HISTOGRAM_SCRIPT@` i think.

2022-06-28 23:09 UTC, andypugh commented
I am glad that you beat me to this. I had started to add the files in the wrong place (directly in debian/extras) forgetting that the files are generated.

2022-06-29 08:21 UTC, petterreinholdtsen commented
[Sebastian Kuzminsky]
> Should be ***@***.***_LATENCY_HISTOGRAM_SCRIPT@` i think.

Absolutely.  Updated patch pushed.

-- 
Happy hacking
Petter Reinholdtsen

2022-07-02 15:41 UTC, merged

2022-07-02 15:41 UTC, jepler commented
Thanks!