Duplicate Strings gmoccapy.pot and linuxcnc.pot
LinuxCNC/linuxcnc pull request #1896
Opened 2022-08-06 19:45 UTC by zz912

The same Strings were generated to gmoccapy.pot and linuxcnc.pot
I inspired here:
https://github.com/LinuxCNC/linuxcnc/pull/542/files

2022-08-08 05:44 UTC, gmoccapy commented
The gmoccapy.glade file belongs to gmoccapy. Thats why I integrated that file to the gmoccapy.pot file.
Changing the Submakefile the way you did, will split the translation of gmoccapy files in two separate files, resulting in one part being in gmoccapy.pot and the other part in linuxcnc.pot.

I agree, that it should not be in both files, but IMHO you should change src/po/Submakefile instead og gmoccapy submakefile.

Norbert

2022-08-08 20:15 UTC, zz912 commented
I would like to ask why gmoccapy.glade is

in PYI18NSRCS
https://github.com/LinuxCNC/linuxcnc/blob/2.8/src/emc/usr_intf/gmoccapy/Submakefile

and at the same time in GMOCCAPY_I18N_SRCS
https://github.com/LinuxCNC/linuxcnc/blob/2.8/src/po/Submakefile

?

2022-08-19 07:12 UTC, zz912 commented
Shall we close this PR saying this FIX is not a good idea?

2022-08-20 19:15 UTC, zz912 commented
@hansu  Can I ask for help? I would like close it, but I dont know what Norberts comment mean.

2022-08-20 19:33 UTC, c-morley commented
Norbert wanted it less overwhelming for people to translate Gmoccapy.
It is easier to translate just a program you use then look all through of linuxcnc's translations.
So he separated it.

He is wanting you not to have some of the Gmoccapy required bits have translation somewhere besides Gmoccapy's translation process. This would undo what he did before.

Maybe the web stuff changes things - I have no opinion of the current right way to go.
But I can say at the time, Gmoccapy got more translations after being separate.

2022-08-20 20:15 UTC, zz912 commented
Splitting POT files is a fantastic thing for translators. I myself think that there should be more such divisions. It's crazy for translators to have phrases from PNCconfig, stepconfig, AXIS gui, plasma gui, ......  in one POT file. I think every GUI should have its own POT file.

Maybe I figured out why we don't understand each other.
I did not adequately describe what my PR does.

The current status in version 2.8 is, same Strings were generated to gmoccapy.pot and linuxcnc.pot.

My PR removes Gmoccapy Strings from linuxcnc.pot
My PR leaves Gmoccapy Strings in gmoccapy.pot

This is same status like in version 2.9

The "PYI18NSRCS" parameter I suppressed goes into linuxcnc.pot.
Line 110
https://github.com/LinuxCNC/linuxcnc/blob/2.8/src/po/Submakefile

2022-08-21 08:42 UTC, hansu commented
> I myself think that there should be more such divisions. It's crazy for translators to have phrases from PNCconfig, stepconfig, AXIS gui, plasma gui, ...... in one POT file. I think every GUI should have its own POT file.

I totally agree. If you want to do a good translation, you can do it only if you translate the GUIs one by one and have the corresponding GUI open at that time.

2022-08-21 12:10 UTC, petterreinholdtsen commented
[Hans Unzner]
> If you want to do a good translation, you can do it only if you
> translate the GUIs one by one and have the corresponding GUI open at
> that time.


This seem to assume that translation is a one time task, while I believe
it is a process where one have to use the translation and revisit the
strings as one learn more.  Requiring translators to have the program
visible while translating is placing an unreasonable burden on the
translator, and the end result would be less translators and less
translations.  Instead we need to make it easy to correct inaccurate
translations and ensure as many as possible are exposed to the
translations to fix issues with them early.

-- 
Happy hacking
Peter Reinholdtsen

2022-08-21 13:17 UTC, hansu commented
>Requiring translators to have the program
visible while translating is placing an unreasonable burden on the
translator, and the end result would be less translators and less
translations. 

Okay, it was maybe not the best wording, but one has to know the context for some strings to translate them the right way, otherwise it would result in a misleading translation that would not help to operate the GUI.

2022-08-21 16:51 UTC, zz912 commented
It's nice that we are discussing translations.
Now there is a topic about splitting POT files. We can make a new Issue or open this problem in the forum where we can discuss it.

However, this is a PR where I excluded Strings from the linuxcnc.pot file because the same Strings are in gmoccapy.pot .

I would like to ask for a decision on whether this PR will be merged into the 2.8 branch or discarded.

2022-08-21 16:51 UTC, petterreinholdtsen commented
[Hans Unzner]
> Okay, it was maybe not the best wording, but one has to know the
> context for some strings to translate them the right way, otherwise it
> would result in a misleading translation that would not help to
> operate the GUI.

I agree.  Which is why people need to use the translated version to find
any issues with it . :)
-- 
Happy hacking
Petter Reinholdtsen

2022-08-21 19:59 UTC, hansu commented
[Norbert]
>I agree, that it should not be in both files, but IMHO you should change src/po/Submakefile instead og gmoccapy submakefile.

At first glance your thoughts make totally sense, but the `src/po/Submakefile` handles the translation stuff for `linuxcnc.pot `  as well as `gmoccapy.pot` while `src/emc/usr_intf/gmoccapy/Submakefile` does other tasks like syntax checking or copying.

My only concern was, that maybe only the string variants in linuxcnc.pot have been translated. But that is irrelevant because gmoccapy takes the strings from gmoccapy.pot anyway.

So it's completely fine for me to merge :slightly_smiling_face:.

2022-08-21 20:58 UTC, zz912 commented
We can continue about splitting *.pot files here:
https://forum.linuxcnc.org/37-international-linuxcnc-users/46703-split-po-files-weblate-manual

2022-08-24 14:42 UTC, jepler requested changes

2022-08-24 14:42 UTC, jepler commented on src/emc/usr_intf/gmoccapy/Submakefile
> +#	emc/usr_intf/gmoccapy/gmoccapy.glade
delete, don't comment out

2022-08-24 14:42 UTC, jepler commented
I don't know if the change is a good one or not, but if it is a good change then the lines should be fully deleted, not just commented out.

2022-08-25 13:56 UTC, jepler commented
Thanks for responding to my review request. I'm not going to merge at this time, there doesn't seem to be consensus about what to do. You can ping me again when there is a clear consensus and this PR reflects it.

2022-08-25 14:17 UTC, zz912 commented
I don't know who to ask for consensus. I'll be happy if it's approved, but I don't mind if it's rejected. This decision blocks me from further work.

2022-08-25 20:10 UTC, hansu commented
These deleted lines made the gmoccapy strings appear in linuxcnc.pot as well in addition to gmoccapy.pot. As only the strings of gmoccapy.pot are taken into account for gmoccapy, I think it's safe to remove them. 
If we let it as it is, there is no malfunction, only double work for translators who do translations on po file base. So a rare case, only applicable for languages not yet in Weblate and for 2.8.

2022-09-08 19:17 UTC, zz912 commented
Can I ask for merge? Is it here anybody, who disagree?

2022-09-08 20:51 UTC, andypugh commented
I don't know enough to decide. I have no objection but would prefer input from the translation team.

2022-09-09 07:59 UTC, petterreinholdtsen commented
[andypugh]
> I don't know enough to decide. I have no objection but would prefer
> input from the translation team.

Not quite sure what you want to hear.  Weblate by default will spread
the same string->translation across any file containing the string, so
moving the string from one file to another or having it both places do
not really affect translators nor Weblate.

Note, there is significant less translation of gmoccapy.pot than
linuxcnc.pot. 6 (7 including the empty Italian) of 19 languages are
missing. see
<URL: https://i18n.debian.org/l10n-pkg-status/l/linuxcnc.html > 
for a nice summary.  

-- 
Happy hacking
Petter Reinholdtsen

2022-09-09 08:23 UTC, zz912 commented
Dear Mr. Petter Reinholdtsen

This PR is for LCNC 2.8, where weblate is fortunately not yet applied.

2022-09-09 08:31 UTC, petterreinholdtsen commented
[zz912]
> This PR is for LCNC 2.8, where weblate is fortunately not yet applied.

Very good.  Then I have no knowledge nor opinion on the matter. I focus
only on 2.9 and beyon.

--
Happy hacking
Petter Reinholdtsen

2022-09-09 18:30 UTC, hansu commented
For me it's fine to merge this.

2022-09-09 18:47 UTC, c-morley commented
What happens translation wise if a gladevcp widher is used in gmoccapy and an other program?
would it require two translations? Is this the problem we are actually talking about?

2022-09-09 19:49 UTC, zz912 commented
To Chris: I opened topic for other language problems here https://forum.linuxcnc.org/37-international-linuxcnc-users/46703-split-po-files-weblate-manual and it is not related to this PR. This PR is only STOP duplicate same strings in linuxcnc.pot and gmoccapy.pot

2022-09-09 20:00 UTC, hansu commented
> What happens translation wise if a gladevcp widget is used in gmoccapy and another program?
> would it require two translations? Is this the problem we are actually talking about?

No, the GladeVCPs are still in linuxcnc.pot. And no, this is only about removing duplicated stings in the pot files.

2022-09-10 00:48 UTC, andypugh commented
> For me it's fine to merge this.
> I just double checked this with a clean build and all the strings are how they should be.

Ok, then please merge it.

2022-09-10 10:12 UTC, hansu commented
Alright.
For details which duplicates of linuxcnc.pot are removed see here:
<details>
  <summary>diff Linuxcnc.pot</summary>

```diff
--- linuxcnc.pot.old	2022-09-10 11:58:54.037001000 +0200
+++ linuxcnc.pot.new	2022-09-10 11:51:58.633001000 +0200
@@ -8,7 +8,7 @@
 msgstr ""
 "Project-Id-Version: PACKAGE VERSION\n"
 "Report-Msgid-Bugs-To: \n"
-"POT-Creation-Date: 2022-09-10 11:58+0200\n"
+"POT-Creation-Date: 2022-09-10 11:29+0200\n"
 "PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
 "Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
 "Language-Team: LANGUAGE <LL@li.org>\n"
@@ -1751,7 +1751,6 @@
 msgstr ""
 
 #: src/hal/utils/meter.c:242 tcl/tklinuxcnc.tcl:793
-#: src/emc/usr_intf/gmoccapy/gmoccapy.glade:8088
 msgid "Hal Meter"
 msgstr ""
 
@@ -2998,7 +2997,6 @@
 msgstr ""
 
 #: src/hal/classicladder/classicladder_gtk.c:883 share/axis/tcl/axis.tcl:1333
-#: src/emc/usr_intf/gmoccapy/gmoccapy.glade:873
 msgid "Preview"
 msgstr ""
 
@@ -3423,7 +3421,7 @@
 msgstr ""
 
 #: src/hal/classicladder/edit_gtk.c:186 src/hal/classicladder/edit_gtk.c:360
-#: tcl/tooledit.tcl:488 src/emc/usr_intf/gmoccapy/gmoccapy.glade:8365
+#: tcl/tooledit.tcl:488
 msgid "Delete"
 msgstr ""
 
@@ -3432,7 +3430,6 @@
 msgstr ""
 
 #: src/hal/classicladder/edit_gtk.c:350
-#: src/emc/usr_intf/gmoccapy/gmoccapy.glade:8382
 msgid "Add"
 msgstr ""
 
@@ -3626,7 +3623,6 @@
 msgstr ""
 
 #: src/hal/classicladder/editproperties_gtk.c:213
-#: src/emc/usr_intf/gmoccapy/gmoccapy.glade:8416
 msgid "Apply"
 msgstr ""
 
@@ -3811,7 +3807,6 @@
 
 #: src/hal/classicladder/manager_gtk.c:72
 #: src/hal/classicladder/manager_gtk.c:234 tcl/bin/halconfig.tcl:196
-#: src/emc/usr_intf/gmoccapy/gmoccapy.glade:4351
 msgid "Main"
 msgstr ""
 
@@ -4452,7 +4447,6 @@
 msgstr ""
 
 #: tcl/bin/genedit.tcl:140 tcl/tklinuxcnc.tcl:775
-#: src/emc/usr_intf/gmoccapy/gmoccapy.glade:7146
 msgid "Settings"
 msgstr ""
 
@@ -5160,7 +5154,7 @@
 msgid "commanded"
 msgstr ""
 
-#: tcl/tklinuxcnc.tcl:1139 src/emc/usr_intf/gmoccapy/gmoccapy.py:621
+#: tcl/tklinuxcnc.tcl:1139
 msgid "joint"
 msgstr ""
 
@@ -5254,11 +5248,10 @@
 msgstr ""
 
 #: tcl/tklinuxcnc.tcl:1954 tcl/ngcgui_ttt.tcl:284
-#: src/emc/usr_intf/gmoccapy/gmoccapy.glade:6888
 msgid "Font"
 msgstr ""
 
-#: tcl/tklinuxcnc.tcl:1961 src/emc/usr_intf/gmoccapy/gmoccapy.glade:5060
+#: tcl/tklinuxcnc.tcl:1961
 msgid "Size"
 msgstr ""
 
@@ -6062,7 +6055,7 @@
 msgid "Linescale"
 msgstr ""
 
-#: tcl/ngcgui_ttt.tcl:178 src/emc/usr_intf/gmoccapy/gmoccapy.glade:5434
+#: tcl/ngcgui_ttt.tcl:178
 msgid "none"
 msgstr ""
 
@@ -6861,7 +6854,6 @@
 #: src/emc/usr_intf/axis/scripts/axis.py:1457
 #: src/emc/usr_intf/axis/scripts/axis.py:3216 share/axis/tcl/axis.tcl:922
 #: share/axis/tcl/axis.tcl:924 share/axis/tcl/axis.tcl:2068
-#: src/emc/usr_intf/gmoccapy/gmoccapy.py:1015
 msgid "Continuous"
 msgstr ""
 
@@ -6972,7 +6964,6 @@
 msgstr ""
 
 #: src/emc/usr_intf/axis/scripts/axis.py:1991
-#: src/emc/usr_intf/gmoccapy/gmoccapy.py:2416
 msgid "No file loaded"
 msgstr ""
 
@@ -7831,11 +7822,11 @@
 msgid "Toggle optional pause [Alt-M 1]"
 msgstr ""
 
-#: share/axis/tcl/axis.tcl:586 src/emc/usr_intf/gmoccapy/gmoccapy.glade:640
+#: share/axis/tcl/axis.tcl:586
 msgid "Zoom in"
 msgstr ""
 
-#: share/axis/tcl/axis.tcl:594 src/emc/usr_intf/gmoccapy/gmoccapy.glade:658
+#: share/axis/tcl/axis.tcl:594
 msgid "Zoom out"
 msgstr ""
 
@@ -8609,7 +8600,6 @@
 msgstr ""
 
 #: src/emc/usr_intf/touchy/touchy.glade:1539
-#: src/emc/usr_intf/gmoccapy/gmoccapy.glade:6135
 msgid "<b>Spindle</b>"
 msgstr ""
 
@@ -8773,7 +8763,6 @@
 msgstr ""
 
 #: src/emc/usr_intf/touchy/touchy.glade:3009
-#: src/emc/usr_intf/gmoccapy/gmoccapy.glade:8071
 msgid "Status"
 msgstr ""
 
@@ -16623,7 +16612,6 @@
 #: src/emc/usr_intf/gscreen/gscreen.py:4261
 #: src/emc/usr_intf/gscreen/gscreen.py:4267
 #: src/emc/usr_intf/gscreen/gscreen.py:4270
-#: src/emc/usr_intf/gmoccapy/gmoccapy.py:3715
 msgid "INFO:"
 msgstr ""
 
@@ -16776,31 +16764,23 @@
 msgstr ""
 
 #: src/emc/usr_intf/gscreen/gscreen.py:3740
-#: src/emc/usr_intf/gmoccapy/dialogs.py:111
-#: src/emc/usr_intf/gmoccapy/dialogs.py:126
-#: src/emc/usr_intf/gmoccapy/dialogs.py:140
 msgid "Operator Message"
 msgstr ""
 
 #: src/emc/usr_intf/gscreen/gscreen.py:3774
 #: src/emc/usr_intf/gscreen/gscreen.py:3778
-#: src/emc/usr_intf/gmoccapy/dialogs.py:178
-#: src/emc/usr_intf/gmoccapy/dialogs.py:182
 msgid "Restart Entry"
 msgstr ""
 
 #: src/emc/usr_intf/gscreen/gscreen.py:3787
-#: src/emc/usr_intf/gmoccapy/dialogs.py:194
 msgid "Up"
 msgstr ""
 
 #: src/emc/usr_intf/gscreen/gscreen.py:3789
-#: src/emc/usr_intf/gmoccapy/dialogs.py:196
 msgid "Enter"
 msgstr ""
 
 #: src/emc/usr_intf/gscreen/gscreen.py:3791
-#: src/emc/usr_intf/gmoccapy/dialogs.py:198
 msgid "Down"
 msgstr ""
 
@@ -17019,28 +16999,24 @@
 msgstr ""
 
 #: src/emc/usr_intf/gscreen/gscreen.glade:1715
-#: src/emc/usr_intf/gmoccapy/gmoccapy.glade:4273
 msgid ""
 "Search\n"
 "  Text:"
 msgstr ""
 
 #: src/emc/usr_intf/gscreen/gscreen.glade:1743
-#: src/emc/usr_intf/gmoccapy/gmoccapy.glade:4203
 msgid ""
 "Replace\n"
 "  Text:"
 msgstr ""
 
 #: src/emc/usr_intf/gscreen/gscreen.glade:1762
-#: src/emc/usr_intf/gmoccapy/gmoccapy.glade:4213
 msgid ""
 "Replace\n"
 "   All"
 msgstr ""
 
 #: src/emc/usr_intf/gscreen/gscreen.glade:1775
-#: src/emc/usr_intf/gmoccapy/gmoccapy.glade:4228
 msgid ""
 "Ignore\n"
 " Case"
@@ -17055,7 +17031,6 @@
 msgstr ""
 
 #: src/emc/usr_intf/gscreen/gscreen.glade:1858
-#: src/emc/usr_intf/gmoccapy/gmoccapy.glade:5538
 msgid "Themes"
 msgstr ""
 
@@ -17068,12 +17043,10 @@
 msgstr ""
 
 #: src/emc/usr_intf/gscreen/gscreen.glade:1951
-#: src/emc/usr_intf/gmoccapy/gmoccapy.glade:5572
 msgid "Warning Audio"
 msgstr ""
 
 #: src/emc/usr_intf/gscreen/gscreen.glade:1961
-#: src/emc/usr_intf/gmoccapy/gmoccapy.glade:5586
 msgid "Alert Audio"
 msgstr ""
 
@@ -17082,7 +17055,6 @@
 msgstr ""
 
 #: src/emc/usr_intf/gscreen/gscreen.glade:2021
-#: src/emc/usr_intf/gmoccapy/gmoccapy.glade:6019
 msgid "Starting RPM"
 msgstr ""
 
@@ -17159,7 +17131,6 @@
 msgstr ""
 
 #: src/emc/usr_intf/gscreen/gscreen.glade:2328
-#: src/emc/usr_intf/gmoccapy/gmoccapy.glade:8106
 msgid "Calibration"
 msgstr ""
 
@@ -17405,12 +17376,10 @@
 msgstr ""
 
 #: src/emc/usr_intf/gscreen/gscreen.glade:3550
-#: src/emc/usr_intf/gmoccapy/gmoccapy.glade:4113
 msgid "Undo"
 msgstr ""
 
 #: src/emc/usr_intf/gscreen/gscreen.glade:3561
-#: src/emc/usr_intf/gmoccapy/gmoccapy.glade:4164
 msgid "Redo"
 msgstr ""
 
@@ -17494,1606 +17463,3 @@
 #: src/emc/usr_intf/gscreen/gscreen2.glade:35
 msgid "screen 2"
 msgstr ""
-
-#: src/emc/usr_intf/gmoccapy/gmoccapy.py:233
-#: src/emc/usr_intf/gmoccapy/gmoccapy.py:238
-msgid "**** GMOCCAPY INI Entry **** \n"
-msgstr ""
-
-#: src/emc/usr_intf/gmoccapy/gmoccapy.py:234
-msgid "user mode selected"
-msgstr ""
-
-#: src/emc/usr_intf/gmoccapy/gmoccapy.py:239
-#, python-brace-format
-msgid "logo entry found = {0}"
-msgstr ""
-
-#: src/emc/usr_intf/gmoccapy/gmoccapy.py:244
-msgid "**** GMOCCAPY INI Entry Error **** \n"
-msgstr ""
-
-#: src/emc/usr_intf/gmoccapy/gmoccapy.py:245
-msgid "Logofile entry found, but could not be converted to path.\n"
-msgstr ""
-
-#: src/emc/usr_intf/gmoccapy/gmoccapy.py:246
-msgid "The file path should not contain any spaces"
-msgstr ""
-
-#: src/emc/usr_intf/gmoccapy/gmoccapy.py:615
-msgid "axis"
-msgstr ""
-
-#: src/emc/usr_intf/gmoccapy/gmoccapy.py:616
-msgid "axes"
-msgstr ""
-
-#: src/emc/usr_intf/gmoccapy/gmoccapy.py:622
-msgid "joints"
-msgstr ""
-
-#: src/emc/usr_intf/gmoccapy/gmoccapy.py:637
-#, python-brace-format
-msgid "Press to home all {0}"
-msgstr ""
-
-#: src/emc/usr_intf/gmoccapy/gmoccapy.py:646
-#: src/emc/usr_intf/gmoccapy/gmoccapy.py:896
-msgid "Press to display previous homing button"
-msgstr ""
-
-#: src/emc/usr_intf/gmoccapy/gmoccapy.py:664
-#, python-brace-format
-msgid "Press to home {0} {1}"
-msgstr ""
-
-#: src/emc/usr_intf/gmoccapy/gmoccapy.py:677
-#: src/emc/usr_intf/gmoccapy/gmoccapy.py:920
-msgid "Press to display next homing button"
-msgstr ""
-
-#: src/emc/usr_intf/gmoccapy/gmo [...]

2022-09-10 10:14 UTC, merged

2022-09-11 10:14 UTC, gmoccapy commented
It is very frustrating to see that you now splited the gmoccapy translation in two pot files.

gmoccapy.glade is the main screen from gmoccapy! It is no widget it is the main screen!!
All the effort I have done to translate the GUI in different languages has become now much more complicated. I explained all at the beginning of this discussion why I did all the thinks.

I agree that it should not be in both submake files, but IT BELOGNGS TO GMOCCAPY not to linuxcnc.

As I am still out of time I hope someone will revert this change, otherwise I will do that as soon as I have time.

Norbert