debian/control.docs.in - invitations to Weblate
LinuxCNC/linuxcnc pull request #1961
Opened 2022-08-23 11:43 UTC by smoe

More verbose description of why the documentation of LinuxCNC is important.
Added invitations to contribute to Weblate.
Added translation for French documentation (@silopolis, please check, also have a look at the extension of the Spanish, please).

I have intentionally not translate the part mentioning Weblate. Maybe I should have done.

2022-08-23 14:26 UTC, silopolis requested changes
Changed first character of descriptions to capital as it seems appropriate for a "Property: Value" pair.
Translated the remaining paragraphs for french and spanish

2022-08-23 14:26 UTC, silopolis commented on debian/control.docs.in
> + is sufficient. Please help if you can.
```suggestion
La documentación se preparó recientemente para su traducción asistida por computadora a todos
los demás idiomas en Weblate (https://hosted.weblate.org/projects/linuxcnc/linuxcnc-docs/).
Necesitamos ayuda con la confirmación manual de la transición automatizada de la traducción
manual anterior al español, para lo cual una comprensión pasiva del idioma es suficiente.
Por favor ayuda si puedes.
```

2022-08-23 14:26 UTC, silopolis commented on debian/control.docs.in
> +Description: motion controller for CNC machines and robots (Chinese documentation)
```suggestion
Description: Motion controller for CNC machines and robots (Chinese documentation)
```

2022-08-25 16:04 UTC, smoe commented
Squashed everything, line-wrapped, and rebased to master. Fingers crossed, this builds now.

2022-08-26 07:34 UTC, smoe commented
It builds. @SebKuzminsky or @jepler, may I ask either of you to have an extra eye on this one?

2022-08-29 14:38 UTC, smoe commented
Rebased to master (no conflicts), added missing period in top.in, bumped standard to 4.6.1.

2022-08-30 10:12 UTC, smoe commented
Rebased to master because of a tiny conflict.

I just saw that I commited 
[docs: More translation-motivated changes](https://github.com/LinuxCNC/linuxcnc/pull/1961/commits/ffd6a1b89aeb336fa141b5d51e828ccee9c6ae9e)
[ffd6a1b](https://github.com/LinuxCNC/linuxcnc/pull/1961/commits/ffd6a1b89aeb336fa141b5d51e828ccee9c6ae9e) to the wrong branch. Those extra changes look sufficiently harmless and they are in a separate commit such that I hope that you allow these to remain in this PR.

2022-08-30 10:29 UTC, petterreinholdtsen commented
[Steffen Möller]
> Those extra changes look sufficiently harmless and they are in a
> separate commit such that I hope that you allow these to remain in
> this PR.

I have no opinion there, but ping me on IRC if you want help moving
those to a separate branch instead.  I can help you with the 'git
checkout -b', 'git reset' and 'git push -f' recipe if you need it.

-- 
Happy hacking
Petter Reinholdtsen

2022-08-31 16:27 UTC, smoe commented
If agreeing with the individual commits, please just accept it.

2022-11-07 20:27 UTC, closed without merging

2022-11-07 20:27 UTC, smoe commented
Translations should likely go elsewhere, no pointer to weblate.