Series of smallish changes - triggered by translations.
LinuxCNC/linuxcnc pull request #1962
Opened 2022-08-23 18:58 UTC by smoe

2022-08-24 06:11 UTC, hansu commented
Will you not rather resolve the merge conflicts for #1926 than creating new ones?

2022-08-24 14:09 UTC, smoe commented
> Will you not rather resolve the merge conflicts for #1926 than creating new ones?

The translations work on every machine whenever I have a spare minute. The changes to the English depend on the machine I am working on.

2022-08-24 17:17 UTC, hansu commented
But you can check out every branch on every machine. I don't see the problem...

2022-08-25 13:03 UTC, smoe commented
I admit that these conflicts get on my nerves, too, so I should consider to adjust my routine.

2022-08-26 14:34 UTC, petterreinholdtsen commented
I had a look at this, and realize I do not know the asciidoc format enough to understand the effect of all the formatting changes.

2022-08-27 10:26 UTC, hansu commented
@smo just to inform you about your homemade conflicts ;-)

2022-08-27 12:12 UTC, hansu requested changes

2022-08-27 12:12 UTC, hansu commented on docs/src/gui/ngcgui.adoc
> +<<<<<<< HEAD
ooops :wink: 


and some further in this file

2022-08-27 12:12 UTC, hansu commented on docs/src/gui/panelui.adoc
> +<<<<<<< HEAD
in this file as well

2022-08-27 12:12 UTC, hansu commented on docs/src/gui/panelui.adoc
> +>>>>>>> 2bd0b2e818 (More changes, many python -> Python)
this is duplicated

2022-08-27 12:12 UTC, hansu commented on docs/src/gui/qtvcp-widgets.adoc
> +<<<<<<< HEAD
here as well

2022-08-27 12:12 UTC, hansu commented on docs/src/gui/qtvcp-widgets.adoc
> +>>>>>>> 2bd0b2e818 (More changes, many python -> Python)
duplicated

2022-08-27 12:12 UTC, hansu commented on docs/src/gui/qtvcp-widgets.adoc
> +OriginOfsetView has properties that can be set in designer, in Python
```suggestion
OriginOffsetView has properties that can be set in designer, in Python
```

2022-08-27 12:12 UTC, hansu commented on docs/src/gui/qtvcp-widgets.adoc
> +It returns the entry via STATUS messages using a Python DICT.
```suggestion
It returns the entry via STATUS messages using a Python dict.
```

2022-08-27 12:12 UTC, hansu commented on docs/src/gui/qtvcp-widgets.adoc
> +It returns the entry via STATUS messages using a Python DICT.
```suggestion
It returns the entry via STATUS messages using a Python dict.
```

2022-08-27 12:14 UTC, hansu commented
Nice work and thanks for immediately rebasing this :slightly_smiling_face:

2022-08-27 12:54 UTC, smoe commented on docs/src/gui/panelui.adoc
> +<<<<<<< HEAD
Done.

2022-08-27 12:55 UTC, smoe commented on docs/src/gui/qtvcp-widgets.adoc
> +<<<<<<< HEAD
done.

2022-08-27 12:58 UTC, smoe commented on docs/src/gui/panelui.adoc
> +>>>>>>> 2bd0b2e818 (More changes, many python -> Python)
done

2022-08-27 18:42 UTC, smoe commented
Let me squash these.

2022-08-27 18:46 UTC, hansu commented on docs/src/gui/ngcgui.adoc
> +AXIS, GScreen, or Touchy GUIs.  (See additional sections below for additional
```suggestion
AXIS, gscreen, or Touchy GUIs.  (See additional sections below for additional
```

2022-08-27 18:46 UTC, hansu commented on docs/src/gui/ngcgui.adoc
> +Examples are included for the AXIS, Touchy, GScreen, and GMOCCAPY.
```suggestion
Examples are included for the AXIS, Touchy, gscreen, and GMOCCAPY.
```

2022-08-27 18:46 UTC, hansu commented on docs/src/gui/ngcgui.adoc
> +  GUI that supports embedding of GladeVCP applications AXIS, Touchy, GScreen
```suggestion
  GUI that supports embedding of GladeVCP applications AXIS, Touchy, gscreen
```

2022-08-27 18:46 UTC, hansu approved these changes

2022-08-27 18:47 UTC, hansu commented
> Let me squash these.

Sure, it's your branch :wink:

2022-08-27 19:22 UTC, smoe commented
Argh. @hansu It seems like I have accidentially overwritten the most commits of yours when I force-uploaded my local rebase. From what I see in my inbox, this was about how Gscreen should be spelled. This is highly inconsistent, throughout LinuxCNC documentation and apps :o/ 

$ grep -r gscreen ../docs/|grep -v pot|grep -v po | wc
grep: ../docs/man/index.db: binary file matches
    397    6672   62334
$ grep -r Gscreen ../docs/|grep -v pot|grep -v po | wc
    582   11696   94301

2022-08-27 19:37 UTC, hansu commented
> Argh. @hansu It seems like I have accidentially overwritten the most commits of yours when I force-uploaded my local rebase. From what I see in my inbox, this was about how Gscreen should be spelled. This is highly inconsistent, throughout LinuxCNC documentation and apps :o/
> 
> $ grep -r gscreen ../docs/|grep -v pot|grep -v po | wc grep: ../docs/man/index.db: binary file matches 397 6672 62334 $ grep -r Gscreen ../docs/|grep -v pot|grep -v po | wc 582 11696 94301

No worries, I still have it locally.

Yes the spelling of gscreen should be unified. But GScreen at least not ;-).

2022-08-27 19:45 UTC, hansu commented
But your commit message doesn't fit any longer :laughing:

2022-08-28 08:23 UTC, merged