misc changes while translating (smoe:Docs29 misc pc 1)
LinuxCNC/linuxcnc pull request #2207
Opened 2022-12-15 14:41 UTC by smoe

Series of smallish changes - (almost no) semantic line breaks.

2022-12-28 18:08 UTC, hansu requested changes

2022-12-28 23:34 UTC, smoe commented on docs/src/gcode/g-code.adoc
> +* `G93` - is Inverse Time Mode.
This likely was inconsistent prior to me editing already. I like the idea that G93 is a command that should be printed in monospace. I likely eventually observed that inconsistency myself and then stopped and am at ease with whatever decision you make, just do not want to see those patches delayed. Let's just decide how it shall be and we then have more dedicated patches triggered by that decision.

2022-12-29 00:28 UTC, smoe commented on docs/src/remap/remap.adoc
> +  Python. Use this if you don_t need an NGC procedure, or NGC is
done

2022-12-29 23:21 UTC, smoe commented
@hansu - I do not know about what requested change there remains unanswered.

2022-12-30 22:16 UTC, smoe commented
@hansu - rebased, also squashed.

2023-01-01 16:41 UTC, hansu commented
@smoe Again conflicts to resolve...

2023-01-02 01:04 UTC, smoe commented
@hansu - conflicts resolved and building

2023-01-03 09:28 UTC, hansu commented
The thing with the monospaced highlighting especially for the G-codes. 
The problem (at least for me) is that the monospaced font has different proportions than the regular one. So with the same font size, the characters are smaller (height). So a bit unsuitable if a highlighted character is smaller than the rest.
But if I increase the font size, the monospace text is then wider than the regular one. Looks also weird. For single chars like "G1" it looks good, bot not for longer text:
![grafik](https://user-images.githubusercontent.com/67957916/210275526-d726fc34-8ea8-4f09-a197-61903ba62ccf.png)

I have no really good solution for that. The easiest fix for highlighting would be for
- only a few chars: italic 
- longer code names: monospaced

2023-01-03 18:53 UTC, smoe commented
I have no immediate answer.  Important for me is to distinguish anything that is coded from the text that task about it. If the semantics are correct then I can live with most optical representations as long as they consistent.

That said, it may be wrong to highlight a command as `typed` just when expressing that the command is implemented very nicely. Maybe it would be sufficient to just have the cross-link on it?

But then, I also liked how we have now all the pin names identified, even when just talking about them. For me this is helpful.

What is it that we really want? Using LaTeX with a function that knows how to present the pin names/commands?

2023-01-07 17:13 UTC, silopolis commented
Can't the CSS be adjusted with a smaller size for mono fonts?
Or use better quality web fonts?

2023-01-07 18:02 UTC, hansu commented
> Can't the CSS be adjusted with a smaller size for mono fonts?

The example shows an enlarged monospaced font. With a smaller size te character hight is lower than the regular font.

 >Or use better quality web fonts?
No idea what font can be used which every browser supports. Or we provide an own font.

2023-01-08 09:03 UTC, silopolis commented
Le sam. 7 janv. 2023 à 19:02, Hans Unzner ***@***.***> a
écrit :

> Can't the CSS be adjusted with a smaller size for mono fonts?
>
> The example shows an enlarged monospaced font. With a smaller size te
> character hight is lower than the regular font.
>

Oh didn't understood sorry

Or use better quality web fonts?
> No idea what font can be used which every browser supports. Or we provide
> an own font.
>
>
Aren't web fonts downloaded by browser on demand?

2023-01-08 10:03 UTC, hansu commented
>Aren't web fonts downloaded by browser on demand?

I think so. But for offline docs we should provide the font.

2023-01-21 13:04 UTC, hansu commented
I was so free and did a clean rebase (and add a commit on top)

2023-01-21 14:04 UTC, merged