Change HAL pin type for hy_gt_vfd.fault-info from float to u32
LinuxCNC/linuxcnc pull request #2209
Opened 2022-12-16 07:00 UTC by petterreinholdtsen

Restructure code to handle two types of HAL pin types for modbus register.

Fixes #2206.

2022-12-16 07:01 UTC, petterreinholdtsen commented
I would like someone who know this component a little better to see if this is a wanted change and if the approach taken is a good one.

2022-12-16 09:32 UTC, andypugh commented
Looks reasonable, though possibly the input_terminal should be int too. (but then I suspect that output_terminal isn't really handled at all in any useful way)

2022-12-16 16:21 UTC, SebKuzminsky commented
Looks good to me.  I no longer have access to this VFD to test it, I'm interested to see if it works for @persei802.

I also don't have access to the manual, but I wonder if the fault-info register is a bitmap of different errors; if so it might make sense to break it out into a bunch of bit pins identifying the different errors.

2022-12-17 05:04 UTC, persei802 commented
That is correct. There are 26 bits indicating a fault condition. In my GUI, I convert this register to a hex value so it's easy to determine which bits are set. The manual doesn't actually explain what each of these bits mean, except that 0x00 is no fault. In my personal opinion, it is not useful to break them out into individual HAL pins.
Jim

2022-12-17 15:14 UTC, SebKuzminsky requested changes
Looks good, except for the nitpick about changelog location.

2022-12-17 15:14 UTC, SebKuzminsky commented on docs/src/man/man1/hy_gt_vfd.1.adoc
> +        done 2022-12-17.
This kind of user-facing changelog information belongs in [Updating LinuxCNC](http://linuxcnc.org/docs/devel/html/getting-started/updating-linuxcnc.html), not in the manpage.

2022-12-17 19:56 UTC, c-morley commented
Could this be done with s32 rather then u32 or do you need to extra range? 
u32 is awkward to use in many components ie classicladder.

2022-12-17 20:43 UTC, andypugh commented
I think U32 is the right choice if the intention is to break it out into bits. It matches the bitslice component. 
It's a bitmap, so signed does not make any sense (even if it is only 16 bits)

2022-12-17 20:45 UTC, c-morley commented
Then maybe have both pins? HAL pins are cheap.

2022-12-17 20:50 UTC, petterreinholdtsen commented
[Sebastian Kuzminsky]
> @SebKuzminsky requested changes on this pull request.
>
> Looks good, except for the nitpick about changelog location.
>
>> +        The VFD's fault info register.  The type of this register was
> +        changed from float to u32 in version 2.10.  The commit was
> +        done 2022-12-17.
>
> This kind of user-facing changelog information belongs in [Updating
> LinuxCNC](http://linuxcnc.org/docs/devel/html/getting-started/updating-linuxcnc.html),
> not in the manpage.

The idea is to make sure those using the fault-info value today who
experience unexpected behaviour when they upgrade to 2.10, should be
able to find a clue why in the man page of the failing module.

I find it valuable when information about when a feature was introduced
is included in manual pages, like it is for example in several linux
syscall man pages and debhelper(7).

I have nothing against listing it in
getting-started/updating-linuxcnc.adoc.

-- 
Happy hacking
Petter Reinholdtsen

2022-12-18 16:05 UTC, petterreinholdtsen commented
[c-morley]
> Then maybe have both pins? HAL pins are cheap.

I left the old fault-info float pin alone, and introduced a new
fault-info-bits pin instead, to stay backwards compatible while also
providing a u32 with easier interpretation of the error bits.  Updated
documentation to match.

-- 
Happy hacking
Petter Reinholdtsen

2022-12-18 19:05 UTC, c-morley commented
Ahh I see, that works too.

2022-12-18 20:00 UTC, persei802 commented
I misspoke earlier. This register has 26 fault codes, not bits. It is a 16 bit register. Anyway, I ran Petter's modified code and it works fine. I have no further issues with this component.

2022-12-18 21:12 UTC, SebKuzminsky commented on docs/src/man/man1/hy_gt_vfd.1.adoc
> +        done 2022-12-17.
The patch was reworked to not break backward compatibility, so no note is needed in `Updating LinuxCNC`.

2022-12-18 22:41 UTC, petterreinholdtsen commented
[Jim]
> I misspoke earlier. This register has 26 fault codes, not bits. It is
> a 16 bit register. Anyway, I ran Petter's modified code and it works
> fine. I have no further issues with this component.

Aha.  Adjusted documentation to drop the 'bit' claim.  Where is the list
of fault codes documnented?

-- 
Happy hacking
Petter Reinholdtsen

2022-12-18 23:01 UTC, persei802 commented
They are in the GT Series Inverter Manual.
![fault_codes](https://user-images.githubusercontent.com/56328463/208323864-373017fe-476d-4236-9ad0-8dc03cba6c16.png)

2022-12-19 07:38 UTC, petterreinholdtsen commented
[Jim]
> They are in the GT Series Inverter Manual.

Thank you.  Added this reference to the man page, and renamed the new
u32 pin from fault-info-bits to fault-info-code, as it is not a bit
field.

I believe this is ready for merging.
-- 
Happy hacking
Petter Reinholdtsen

2022-12-19 10:14 UTC, merged