docs: semantic line breaks, bit of syntax. (smoe/docs29_mac_11)
LinuxCNC/linuxcnc pull request #2241
Opened 2023-01-03 20:27 UTC by smoe

2023-01-04 18:29 UTC, hansu requested changes

2023-01-04 18:29 UTC, hansu commented on docs/src/plasma/plasma-cnc-primer.adoc
> +* 0 V 121.6 kHz (1/32 3.8 kHz = 3800 Hz)
This is misleading (and mathematically wrong).
Either 29 kHz or 29000 Hz. I think our users are tough enough to know that.
```suggestion
* Full scale ≙ 928 kHz (1/32 29 kHz)
* 0 V ≙ 121.6 kHz (1/32 3.8 kHz)
```

2023-01-04 19:12 UTC, smoe commented
I have some good confidence that I have not introduced anything that was mathematically wrong, just the whole paragraph is so unfortunate. My interpretation is that we are supposed to learn that the value for 1V change is HzPerVolt = (Hz~max~ - Hz~min~) / (V~max~ - V~min~), which is not stated anywhere. And the reverse calculation for the 5V example would then be Hz~min~ + 5*HzPerVolt - I did not look at the value they came up with. If this is not how it is supposed to work then I think I would want to have another scale that does work linearly :)

2023-01-09 20:10 UTC, smoe commented
Resolved conflict (which implied a rebase on 2.9).

2023-01-15 17:26 UTC, hansu commented
> I have some good confidence that I have not introduced anything that was mathematically wrong, just the whole paragraph is so unfortunate. 

I mean this:

`Full scale 928 kHz (1/32 29 kHz = 29000 Hz)`

and this would be interpreted as

`Full scale 928 kHz (1/32 * 29 kHz = 29000 Hz)`

But `1/32 * 29 kHz ≠ 29000 Hz`



So just drop the "= 29000 Hz"

2023-01-16 01:03 UTC, smoe commented
How about
`Full scale 928 kHz ( * 1/32 = 29 kHz = 29000 Hz)`

2023-01-18 17:07 UTC, hansu commented
> How about `Full scale 928 kHz ( * 1/32 = 29 kHz = 29000 Hz)`

:+1: 
That is at least correct even though I have no idea about the relevance of the 1/32 value.

2023-01-18 18:56 UTC, smoe commented
The original is already bad and I suggest to just accept my change to then jointly improve it afterwards.

2023-01-19 19:36 UTC, hansu commented on docs/src/plasma/plasma-cnc-primer.adoc
> +* 0 V ≙ 121.6 kHz (1/32 3.8 kHz)
```suggestion
* Full scale ≙ 928 kHz (928 kHz/32 = 29 kHz)
* 0 V ≙ 121.6 kHz (121.6 kHz/32 = 3.8 kHz)
```

2023-01-19 19:38 UTC, hansu commented
> The original is already bad and I suggest to just accept my change to then jointly improve it afterwards.

Yes, then please add that or my most recent suggestion.
My first suggestion was unfortunately wrong :innocent:

2023-01-19 20:19 UTC, smoe commented
You suggestions was lovely. Committed.

2023-01-19 20:24 UTC, hansu approved these changes

2023-01-19 20:25 UTC, hansu commented
> You suggestions was lovely. Committed.

Thanks

I'll merge some of your PR's tomorrow when I can merge them up directly after to avoid those conflicts we had.

2023-01-20 19:01 UTC, merged