docs: misc changes triggered while revisiting translations (smoe:docs29_mac_104)
LinuxCNC/linuxcnc pull request #2592
Opened 2023-07-21 16:49 UTC by smoe

Not too much left.

2023-08-03 15:35 UTC, hansu requested changes
And please rebase to resolve the conflict.

2023-08-03 15:35 UTC, hansu commented on docs/src/code/writing-tests.adoc
> +.Arguments acceppted by The _runtests_ script, see the output
```suggestion
.Arguments accepted by The _runtests_ script, see the output
```

2023-08-03 15:35 UTC, hansu commented on docs/src/ladder/classic-ladder.adoc
> +* `%C`__xx__`.P` - Counter _xx_ preset (integer, read or write)
```suggestion
* '%C'__xx__`.P` - Counter _xx_ preset (integer, read or write)
```
Please leave them in italic to keep it consistent

2023-08-03 15:35 UTC, hansu commented on docs/src/ladder/classic-ladder.adoc
> +* `F` - overflow (output) will be true when the count rolls over from 9999 to 0.
```suggestion
* 'F' - overflow (output) will be true when the count rolls over from 9999 to 0.
```
Please leave them in italic to keep it consistent with the rest

2023-08-04 09:33 UTC, smoe commented
@hansu, I messed up, performed the rebase without first pulling your changes. Please kindly have a look at [a1359dd](https://github.com/LinuxCNC/linuxcnc/pull/2592/commits/a1359dddab1fc8cc15fc7f17336d7213a13da452) to ensure that this addresses all in the way you wanted this to be addressed.

2023-08-04 09:45 UTC, hansu commented
> @hansu, I messed up, performed the rebase without first pulling your changes. Please kindly have a look at [a1359dd](https://github.com/LinuxCNC/linuxcnc/pull/2592/commits/a1359dddab1fc8cc15fc7f17336d7213a13da452) to ensure that this addresses all in the way you wanted this to be addressed.

I haven't done any changes to your branch. But the change from my first comment seems got lost.

2023-08-04 10:17 UTC, smoe commented
> > @hansu, I messed up, performed the rebase without first pulling your changes. Please kindly have a look at [a1359dd](https://github.com/LinuxCNC/linuxcnc/pull/2592/commits/a1359dddab1fc8cc15fc7f17336d7213a13da452) to ensure that this addresses all in the way you wanted this to be addressed.
> 
> I haven't done any changes to your branch. But the change from my first comment seems got lost.

Those changes from your comments I have meant to have reintroduced in [a1359dd](https://github.com/LinuxCNC/linuxcnc/pull/2592/commits/a1359dddab1fc8cc15fc7f17336d7213a13da452) . I had felt just fine wrt having addressed all issues, just I was not sure if I was interpreting all your changes correctly. What change from your first comment are you referring to?

2023-08-04 10:42 UTC, hansu commented on docs/src/code/writing-tests.adoc
> +.Arguments acceppted by The _runtests_ script, see the output from `scripts/runtests -h` for the authoritative list.
This one:

```suggestion
.Arguments accepted by the _runtests_ script, see the output from `scripts/runtests -h` for the authoritative list.
```

2023-08-04 11:28 UTC, smoe commented
Accepted your suggested change, and also pulled it into my local repository, just to be sure :)

2023-08-04 11:30 UTC, smoe commented
There is no docs29_mac_105 branch on my side, so this may indeed be the last change from my side that would not contribute some content. Happy!

2023-08-04 11:37 UTC, hansu commented
> There is no docs29_mac_105 branch on my side, so this may indeed be the last change from my side that would not contribute some content. Happy!

We will see ;-)

2023-08-04 11:37 UTC, hansu approved these changes

2023-08-04 22:01 UTC, merged