motion.c: Correct copy-paste errors in handling of miscellanous error inputs
LinuxCNC/linuxcnc pull request #2780
Opened 2023-12-11 12:57 UTC by ArchMachineCo

Correction to lines 348-351 to fix error when using "names_misc_errors" to create named misc error pins.

2023-12-12 19:46 UTC, hansu commented
Thanks for your contribution!
I cannot say anything about the content, but it would be nice to have a more meaningful title and commit message.

2023-12-13 09:07 UTC, havardAasen commented on src/emc/motion/motion.c
> +    num_misc_error = (num_misc_error > count_names(names_misc_errors)) ? num_misc_error : count_names(names_misc_errors);
I can't see how this is correct, the way this has been written, line 350 is totally redundant, `num_misc_error` will always be `count_names(names_misc_errors)`.

2023-12-13 09:14 UTC, havardAasen requested changes
Do we know the original intent with this block? I mean, it compares the numbers of output names  to input names.

2023-12-13 10:12 UTC, havardAasen commented
I've read through it again, I believe the change you do on line 349 is correct, but line 350 should be removed, I also think this should be targeted for 2.9, though @andypugh might want the final say on that.

2023-12-14 13:31 UTC, ArchFabricationAndMachine commented
> Do we know the original intent with this block? I mean, it compares the numbers of output names to input names.

The purpose of this portion of the code is to set the number of misc_error pins. Currently, its uzing the wrong variables in its comparison.

Misc_error pins are created by either using **num_misc_error=x**, or by using **name_misc_errors="error1,error2...."**, but you cannot use both.

So there is a check to see if **num_misc_error** is used on line 344, and then if **num_misc_error** is used, it sets the number of misc error pins = to the value of **num_misc_error**.

If **name_misc_errors** is used, then it **SHOULD** set the number of misc error pins equal to the count of names in the array **name_misc_errors**.

Utilization of **num_misc_error**, AND **name_misc_errors** are both good options, and should remain in the code, the problem currently is that if you specify **name_misc_errors="error1,error2....."**, the number of misc error pins is set to the count of names in the array of digital output pins (**names_dout**).

2023-12-14 14:46 UTC, andypugh commented
This looks like a simple copy/paste error from duplicating the digital IO pins. 

But it's all a bit of a mess. 

````
static int num_misc_error = DEFAULT_MISC_ERROR;	/* default number of misc errors */
RTAPI_MP_INT(num_misc_error, "number of misc error inputs");
...
  if(num_misc_error && (names_misc_errors[0])){
    rtapi_print_msg(RTAPI_MSG_ERR, _("MOTION: Can't specify both names and number for misc error\n"));
    return -1;
  }
  else if(names_misc_errors[0]){
    num_misc_error = count_names(names_dout);
    num_misc_error = (num_misc_error > count_names(names_din)) ? num_misc_error : count_names(names_din);
  }
  else if(!num_misc_error){
    num_misc_error = DEFAULT_MISC_ERROR;
  }

````

If DEFAULT_MISC_ERROR was ever > 0 then in the case where an error name was given, the first conditional would be satisfied, and an error message would be given, disallowing the use of names. 

Then, whilst DEFAULT_MISC_ERROR == 0, the last condition always passes, but has no effect. 

I will try to create a proper fix.

2023-12-15 17:41 UTC, andypugh commented
I think that this is closed by my similar, but different, fix https://github.com/LinuxCNC/linuxcnc/commit/74288982e684e03b567d9850efdd105dc209b1f4

2023-12-15 17:41 UTC, closed without merging

2023-12-15 18:53 UTC, ArchMachineCo commented
Awesome, thanks so much! 

Excuse my noob-ness, but how do I go about getting these changes on my machine?

2023-12-15 22:21 UTC, andypugh commented
If you wait a few days there should be a new 2.9.2 release (There is a Debian-related issue that I am not sure how to address) 
If you don't want to wait that long, then you can add the buildbot to your apt sources.list, of just grab the latest .deb file and install that. http://buildbot2.highlab.com