docs: src/man/man9 - formatting
LinuxCNC/linuxcnc pull request #3050
Opened 2024-08-02 14:00 UTC by smoe

Thinking to have completed the review of the formatting in src/man/man9.

2024-08-02 17:47 UTC, petterreinholdtsen commented
The github CI seem to fail on this change.  I guess it need to be fixed before it can be merged.

2024-08-03 07:53 UTC, hansu requested changes
Thanks a lot for fixing this!

I marked the spots where the build fails...

2024-08-03 07:53 UTC, hansu commented on docs/src/man/man9/hal_bb_gpio.9.adoc
> +>>>>>>> e0fabd0926 (docs: src/man/man9 - formatting)
here

2024-08-03 07:54 UTC, hansu commented on docs/src/man/man9/encoder_ratio.9.adoc
> +>>>>>>> e0fabd0926 (docs: src/man/man9 - formatting)
here

2024-08-03 07:56 UTC, hansu commented on docs/src/man/man9/hal_parport.9.adoc
> +>>>>>>> e0fabd0926 (docs: src/man/man9 - formatting)
here

2024-08-03 07:56 UTC, hansu commented on docs/src/man/man9/hal_parport.9.adoc
> +>>>>>>> e0fabd0926 (docs: src/man/man9 - formatting)
here

2024-08-03 07:56 UTC, hansu commented on docs/src/man/man9/hal_parport.9.adoc
> +>>>>>>> e0fabd0926 (docs: src/man/man9 - formatting)
here

2024-08-03 07:56 UTC, hansu commented on docs/src/man/man9/hal_parport.9.adoc
> +>>>>>>> e0fabd0926 (docs: src/man/man9 - formatting)
here

2024-08-03 09:33 UTC, smoe commented
I have fixed those oversights (and one more :-) ) and then rebased to a refreshed master. 

There is some trouble ahead since for some unknown reason we now get an increased sensitivity on line breaks again. I have a hunch that the parsing of lines starting with something `*bold*`, i.e. with an asterisk, are somehow mistaken for something else that triggers mid-sentence line breaks now. We have some 600 translations now suffering under that symptom.

2024-08-03 09:56 UTC, hansu commented
And it seems that we hove some limitations now - e.g. bold tex in the NAME section is still ignored. See counter.9.adoc.

I continued based on your work with further fine-tuning (
https://github.com/hansu/linuxcnc/commit/aafbd8e5be26b4771db2193424cdeb63fd96de5e). I will commit that after this fix is merged.

2024-08-03 10:16 UTC, merged