Docs man adoc 20240813 2
LinuxCNC/linuxcnc pull request #3110
Opened 2024-09-12 15:03 UTC by smoe

I took my local version of the https://github.com/LinuxCNC/linuxcnc/pull/3066 and rebased it against master. Added another patch to remove empty blanks at the end of lines. Now looks clean, no exact idea what I did differently.

@petterreinholdtsen , @hansu , Please kindly review this one and then I see what I can do to save what is still important n https://github.com/LinuxCNC/linuxcnc/pull/3066 .

Many thanks,
Steffen

2024-09-12 15:50 UTC, smoe commented
The error is not caused by this PR:
```
Skipping disabled test: /home/runner/work/linuxcnc/linuxcnc/tests/save.1
Running test: /home/runner/work/linuxcnc/linuxcnc/tests/single-step
*** /home/runner/work/linuxcnc/linuxcnc/tests/single-step: XFAIL: test run exited with 1
************** result:
        Machine configuration file is 'test.ini'
        Starting LinuxCNC...
        linuxcncsvr (169910) emcsvr: machine 'unknown'  version '1.1'
        linuxcnc TPMOD=tpmod HOMEMOD=homemod EMCMOT=motmod
        milltask (169923) task: machine 'unknown'  version '1.1'
        emc/task/taskclass.cc 187: can't load tool table.
        Found file(LIB): /home/runner/work/linuxcnc/linuxcnc/lib/hallib/core_sim.hal
        USRMOT: ERROR: command 30 timeout
        emcMotionInit: emcTrajInit failed
        task: main loop took 0.018239 seconds
        task: main loop took 0.019244 seconds
        Shutting down and cleaning up LinuxCNC...
        task: 0 cycles, min=0.000004, max=0.019244, avg=-1.000000, 2 latency excursions (> 10x expected cycle time of 0.001000s)
        LinuxCNC terminated with an error.  You can find more information in the log:
            /home/runner/linuxcnc_debug.txt
        and
            /home/runner/linuxcnc_print.txt
        as well as in the output of the shell command 'dmesg' and in the terminal
************** stderr:
        + linuxcnc -r test.ini
        Note: Using POSIX non-realtime
        emc/tooldata/tooldata_common.cc, 304: Failed to open tool table file 'simpockets.tbl': No such file or directory
        emc/tooldata/tooldata_common.cc, 304: Failed to open tool table file 'simpockets.tbl': No such file or directory
        link (updating variable file): No such file or directory
        timeout in wait_complete_step()
        Note: Using POSIX non-realtime
**************
Running test: /home/runner/work/linuxcnc/linuxcnc/tests/source.0
```

2024-09-13 19:26 UTC, petterreinholdtsen commented
[Steffen Möller]
> The error is not caused by this PR:

Yes, there is a race condition in the single-step test.  I restarted the
test and now it succeeded.

I do unfortunately not have time to review these changes for a while.  I
hope someone can have a look.

-- 
Happy hacking
Petter Reinholdtsen

2024-09-27 14:35 UTC, hansu requested changes
What is CMS_buffer.eps?

Please also remove the asterisks from linuxcncrsh.1.adoc:58 while you are at it :)


```diff
To use linuxcncrsh instead of a normal LinuxCNC GUI like AXIS or Touchy,
specify it in your INI file like this:

----
-*[DISPLAY]*
+[DISPLAY]

-*DISPLAY=linuxcncrsh*
+DISPLAY=linuxcncrsh
----
```

2024-09-27 14:35 UTC, hansu commented on docs/src/gui/gscreen.adoc
> +https://wiki.gnome.org/Attic/GnomeArt/Tutorials/GtkThemes[GTK Themes],
This space should stay

2024-09-27 14:35 UTC, hansu commented on docs/src/code/building-linuxcnc.adoc
>    To make use of the realtime capabilities of LinuxCNC, certain parts of LinuxCNC need to run with root privileges.
The dots doesn't make sense here at all.

2024-09-27 14:35 UTC, hansu commented on docs/src/man/man1/linuxcncrsh.1.adoc
> +  Defaults to 'emc.ini' if omitted.
```suggestion
  Defaults to `emc.ini` if omitted.
```

2024-09-27 16:40 UTC, smoe commented
> What is CMS_buffer.eps

It is the DIA (https://en.wikipedia.org/wiki/Dia_(software))-generated post script from which https://github.com/LinuxCNC/linuxcnc/blob/master/docs/src/code/CMS_buffer.png is derived. The EPS file itself is not used.

2024-09-27 16:40 UTC, smoe commented
Looking at the bad quality of the PNG, it may be worthwhile to have a second look at my idea to remove the EPS.

2024-09-28 09:16 UTC, andypugh commented
Would changing the EPS to an SVG work? (Do our tools display SVG? Web browsers display them by default)

2024-09-28 11:32 UTC, smoe commented
> Would changing the EPS to an SVG work?
Yes, nice idea, GIMP can do that, I am sure. Let me provide that alternative - and please also tell me if anything else should be changed in that image at that opportunity :-)

> (Do our tools display SVG? Web browsers display them by default)
I do not know, but the PNG I'll make sure to look better.

2024-09-29 13:01 UTC, smoe commented
> Would changing the EPS to an SVG work? (Do our tools display SVG? Web browsers display them by default)
The SVG looks nice in inkscape and the PNG is also refreshed.
Have rebased to master, have addressed all of Hansu's changes, except for the one still disputed newline one :-) , and added some more lines on the introduction of linuxcncrsh.1 (feeling that tool to be a bit underrated).

2024-09-29 13:21 UTC, hansu commented on docs/src/gui/gscreen.adoc
> +https://wiki.gnome.org/Attic/GnomeArt/Tutorials/GtkThemes[GTK Themes],
This one is still remaining

2024-09-30 09:06 UTC, smoe commented
The error in debian:bookworm is triggered by the tests:
```
Running test: ./tests/single-step
*** ./tests/single-step: XFAIL: test run exited with 1
************** result:
        Machine configuration file is 'test.ini'
        Starting LinuxCNC...
        linuxcncsvr (224663) emcsvr: machine 'unknown'  version '1.1'
        linuxcnc TPMOD=tpmod HOMEMOD=homemod EMCMOT=motmod
        milltask (224675) task: machine 'unknown'  version '1.1'
        emc/task/taskclass.cc 187: can't load tool table.
        Found file(LIB): /usr/share/linuxcnc/hallib/core_sim.hal
        USRMOT: ERROR: command 30 timeout
        emcMotionInit: emcTrajInit failed
        task: main loop took 0.018326 seconds
        task: main loop took 0.018875 seconds
        Shutting down and cleaning up LinuxCNC...
        task: 0 cycles, min=0.000004, max=0.018875, avg=-1.000000, 2 latency excursions (> 10x expected cycle time of 0.001000s)
        LinuxCNC terminated with an error.  You can find more information in the log:
            /home/testrunner/linuxcnc_debug.txt
        and
            /home/testrunner/linuxcnc_print.txt
        as well as in the output of the shell command 'dmesg' and in the terminal
************** stderr:
        + linuxcnc -r test.ini
        ERROR: ld.so: object 'libeatmydata.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
        Note: Using POSIX non-realtime
        ERROR: ld.so: object 'libeatmydata.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
        emc/tooldata/tooldata_common.cc, 304: Failed to open tool table file 'simpockets.tbl': No such file or directory
        emc/tooldata/tooldata_common.cc, 304: Failed to open tool table file 'simpockets.tbl': No such file or directory
        ERROR: ld.so: object 'libeatmydata.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
        ERROR: ld.so: object 'libeatmydata.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
        ERROR: ld.so: object 'libeatmydata.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
        ERROR: ld.so: object 'libeatmydata.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
        link (updating variable file): No such file or directory
        line=7; Xpos=5.00; Ypos=0.12; Zpos=0.00; counter=0
```
Tend to think that this PR is not triggering this.

2024-10-04 08:42 UTC, hansu commented
Simply look here: https://linuxcnc.org/docs/devel/html/gui/gscreen.html#_overview

This
>For some info on GTK theming (The sample theme uses the pixmap theme engine), see: [GTK Themes](https://wiki.gnome.org/Attic/GnomeArt/Tutorials/GtkThemes), [Pixmap Theme Engine](https://wiki.gnome.org/Attic/GnomeArt/Tutorials/GtkEngines/PixmapEngine).
2.2. Build a GladeVCP Panel

would turn into
>For some info on GTK theming (The sample theme uses the pixmap theme engine), see: [GTK Themes](https://wiki.gnome.org/Attic/GnomeArt/Tutorials/GtkThemes),[Pixmap Theme Engine](https://wiki.gnome.org/Attic/GnomeArt/Tutorials/GtkEngines/PixmapEngine).
2.2. Build a GladeVCP Panel

2024-10-04 09:19 UTC, smoe commented
> Simply look here: https://linuxcnc.org/docs/devel/html/gui/gscreen.html#_overview
> 
> This
> 
> > For some info on GTK theming (The sample theme uses the pixmap theme engine), see: [GTK Themes](https://wiki.gnome.org/Attic/GnomeArt/Tutorials/GtkThemes), [Pixmap Theme Engine](https://wiki.gnome.org/Attic/GnomeArt/Tutorials/GtkEngines/PixmapEngine).
> > 2.2. Build a GladeVCP Panel
> 
> would turn into
> 
> > For some info on GTK theming (The sample theme uses the pixmap theme engine), see: [GTK Themes](https://wiki.gnome.org/Attic/GnomeArt/Tutorials/GtkThemes),[Pixmap Theme Engine](https://wiki.gnome.org/Attic/GnomeArt/Tutorials/GtkEngines/PixmapEngine).
> > 2.2. Build a GladeVCP Panel

No, it would not?  I mean, have you seen that happening? Definitely does not happen in the vscode preview. The patch intends to remove the blank that is still followed by a newline, not also the newline. We have lines ending with commas or periods all the time that have proper white space following in the HTML/pdf. I yet fail to see (and would want to understand) why is this now special.

?´+ü´[ <- baby-cat just contributed some extra characters ]

If you do not ultimately mind, please just accept the patch. I'll make a $100 donation to FreeCAD if there is no white space in the PDF after that comma ... and likely spend the rest of the year to find the bug in the autodoc parser.

2024-10-04 11:18 UTC, hansu commented
>No, it would not? 

You are right, sorry. I missed the line break and thought just Github editor did the line break :innocent: 
However I still would not trust the VSCode preview as it targets on asciidoctor not asciidoc-py and differs in some border cases.

2024-10-04 11:18 UTC, merged